### ISSUE TITLE
RFE: reading messages up to delimiter in a stream

### ISSUE THREAD

**Issue by mgrouch** [mairas/ReactESP#25]
A lot of streams are messages separated by sequence of delimiter characters. 
it would be nice to have a reaction which can deliver to callback whole message instead of data chunk. 

Something like

MessageReaction app.onMessage(Stream *stream, Delimiter delim, react_callback cb);

thanks

**Comment by mairas** [comment]
This is an issue that can be easily implemented downstream e.g. with SensESP transforms.
