### ISSUE TITLE
Is this project abandoned??

### ISSUE THREAD

**Issue by imoldovavan** [mairas/ReactESP#27]
I don't see any movement in the last 2 years. Has it been moved??

**Comment by mairas** [comment]
It is in active use in [SensESP](https://github.com/SignalK/SensESP/). I realize the documentation or examples aren't great, and those should be improved. I've had intentionally a conservative approach vs. touching the implementation.

One thing I've had in my mind and what I want to do soon is automatic sleeping: the device should go to modem sleep and reduce its clock rate until the next timed reaction needs to be triggered. 

I'm closing this issue but if you have any specific questions, feel free to ask.
